# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Projekt2Dialog
                                 A QGIS plugin
 01000110 01100001 01101010 01101110 01111001 00100000 01110100 01100101 01101110 00100000 01110000 01110010 01101111 01101010 01100101 01101011 01110100 00100000 01110100 01100001 01101011 01101001 00100000 01101110 01101001 01100101 00100000 01111010 01100001 00100000 11000101 10000010 01100001 01110100 01110111 01111001 00101100 00100000 01101110 01101001 01100101 00100000 01111010 01100001 00100000 01110100 01110010 01110101 01100100 01101110 01111001
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-31
        git sha              : $Format:%H$
        copyright            : (C) 2023 by DS, MR, KP 
        email                : 1
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.utils import iface
import numpy as np
from qgis.core import QgsWkbTypes, QgsVectorLayer, QgsVectorFileWriter, QgsProject, Qgis
from qgis.gui import QgsFileWidget
from PyQt5.QtWidgets import QFileDialog
from qgis.PyQt.QtCore import Qt
from qgis.PyQt.QtWidgets import QAction
from qgis.core import QgsProject, QgsGeometry, QgsVectorLayer, QgsFeature, QgsField, QgsFields
from qgis.core import QgsFeature, QgsGeometry, QgsProject
from qgis.gui import QgsRubberBand
from PyQt5.QtGui import QColor
from qgis.core import QgsProject, QgsCoordinateTransform, QgsGeometry,QgsCoordinateReferenceSystem

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Wtyczka_Projekt_2_dialog_base.ui'))


class Projekt2Dialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(Projekt2Dialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.pushButton_calculate.clicked.connect(self.option)
        self.pushButton_clear.clicked.connect(self.clear)
        self.pushButton_add_file.clicked.connect(self.add_file)


    def clear(self):
        self.label_score.setText('')
        self.label_description_of_score.setText('')
        self.label_number_of_points.setText('')
        iface.messageBar().pushInfo('Clear','Console cleaning performed correctly')

    def add_file(self):
        if self.radioButton_txt.isChecked():
            filepath = QFileDialog.getOpenFileName(self, 'Open file')[0]
            self.textEdit_filepath_score.setText(f'{filepath}')
            file=open(filepath,'r')
            wiersze=file.readlines()
            choosen=[]
            for i in wiersze:
                    xyz=i.split(' ')
                    X=xyz[0]
                    Y=xyz[1]
                    Z=xyz[2]
                    if '\n' in Z:
                        Z=Z[:-1]
                    choosen.append([float(X),float(Y),float(Z)])
            iface.messageBar().pushInfo('Success',f'{choosen}')

        elif self.radioButton_csv.isChecked():
            filepath = QFileDialog.getOpenFileName(self, 'Open file')[0]
            self.textEdit_filepath_score.setText(f'{filepath}')
            file=open(filepath,'r')
            wiersze=file.readlines()
            choosen=[]
            for i in wiersze[1:]:
                    xyz=i.split(',')
                    X=xyz[0]
                    Y=xyz[1]
                    Z=xyz[2]
                    if '\n' in Z:
                        Z=Z[:-1]
                    choosen.append([float(X),float(Y),float(Z)])
            iface.messageBar().pushInfo('Success',f'{choosen}')


    def option(self):
            if self.radioButton_height.isChecked():
                # układa punkty w kolejności takiej samej jak id w tabeli atrybutów
                layer = iface.activeLayer()
                choosen = layer.selectedFeatures()
                i=1
                if len(choosen)==0 or len(choosen)==1:
                        iface.messageBar().pushMessage('Please choose more points')   
                        msg = QtWidgets.QMessageBox()
                        msg.setIcon(QtWidgets.QMessageBox.Critical)
                        msg.setText("                     Error                    ")
                        msg.setInformativeText('Option requires at least two points')
                        msg.exec_()
                else:
                    while i<=(len(choosen)-1):
                        delta_h=float((choosen[i].attributes())[3])-float((choosen[0].attributes())[3])
                        iface.messageBar().pushMessage(f'Różnica wysokosci pomiędzy punktami {choosen[0].attributes()[0]} oraz {choosen[i].attributes()[0]} wynosi {delta_h:.3f}')
                        i=i+1
                    iface.messageBar().pushSuccess( 'Succes','Action performed successfully' )
                self.label_score.setText('Result is in the command line') 



            elif self.radioButton_area.isChecked():
                layer = iface.activeLayer()
                choosen = layer.selectedFeatures()
                area=0
                i=0
                while i<=(len(choosen)-1):
                    if float((choosen[i].attributes())[0])==float((choosen[0].attributes())[1]):
                        last_x=float((choosen[-1].attributes())[1])
                        area=area+(float((choosen[1].attributes())[1])-last_x)*float((choosen[0].attributes())[2])
                    elif choosen[i]==choosen[-1]:
                        first_x=float((choosen[0].attributes())[1])
                        area=area+(first_x-float((choosen[-1].attributes())[2]))*float((choosen[-1].attributes())[2])
                    else:
                        delta_x=float((choosen[i+1].attributes())[1])-float((choosen[i-1].attributes())[1])
                        area=area+delta_x*float((choosen[i].attributes())[2])
                    i=i+1
                    if area<0:
                        area=area*-1
                    self.label_description_of_score.setText('Area of the designated area is')
                if self.radioButtona_meters.isChecked():
                    self.label_score.setText(f'{(area/2):.3f} m')
                elif self.radioButtona_ares.isChecked():
                    self.label_score.setText(f'{(area/200):.2f} a')
                elif self.radioButtona_hectares.isChecked():
                    self.label_score.setText(f'{(area/20000):.4f} ha')
                else:
                    self.label_description_of_score.setText('')
                    self.label_score.setText('')
                    msg = QtWidgets.QMessageBox()
                    msg.setIcon(QtWidgets.QMessageBox.Critical)
                    msg.setText("                     Error                    ")
                    msg.setInformativeText('You have to select units of area!!!')
                    msg.exec_()


                if self.radioButton_system.isChecked():
                    if self.radioButton_pl1992.isChecked():
                        # Pobierz aktualnie zaznaczone obiekty z warstwy
                        layer = iface.activeLayer()
                        selected_features = layer.selectedFeatures()

                        # Nowy EPSG kod układu odniesienia
                        new_epsg_code = 2180

                        # Pobierz transformację współrzędnych z obecnego układu odniesienia do nowego
                        crs_src = layer.crs()
                        crs_dst = QgsCoordinateReferenceSystem(f'EPSG:{new_epsg_code}')
                        transform_context = QgsProject.instance().transformContext()
                        coord_transform = QgsCoordinateTransform(crs_src, crs_dst, transform_context)

                        # Zmiana układu odniesienia dla zaznaczonych elementów
                        layer.startEditing()
                        for feature in selected_features:
                            geometry = feature.geometry()
                            geometry.transform(coord_transform)
                            layer.changeGeometry(feature, geometry)
                        layer.commitChanges()

                    elif self.radioButton_pl2000.isChecked():
                        #QgsProject.instance().setCrs(QgsCoordinateReferenceSystem('EPSG:2180'))
                        s=1




            if self.radioButton_polygon.isChecked():
                # Pobierz aktualnie zaznaczone obiekty
                selected_features = iface.activeLayer().selectedFeatures()

                # Stwórz nową warstwę
                new_layer = QgsVectorLayer("Polygon?crs=epsg:2180", "New Layer", "memory")
                provider = new_layer.dataProvider()
                fields = provider.fields()
                new_layer.startEditing()

                # Stwórz poligon na podstawie zaznaczonych punktów
                polygon_points = []
                for feature in selected_features:
                    geom = feature.geometry()
                    polygon_points.append(geom.asPoint())

                polygon = QgsGeometry.fromPolygonXY([polygon_points])

                # Dodaj poligon do warstwy
                new_feature = QgsFeature()
                new_feature.setGeometry(polygon)
                new_layer.addFeature(new_feature)

                # Zakończ edycję i dodaj nową warstwę do projektu
                new_layer.commitChanges()
                QgsProject.instance().addMapLayer(new_layer)

                # Narysuj poligon na widoku mapy
                rubber_band = QgsRubberBand(iface.mapCanvas())
                rubber_band.setToGeometry(polygon, None)
                rubber_band.setColor(QColor(255, 0, 0, 100))  # Ustaw kolor i przezroczystość poligonu
                rubber_band.setWidth(1)
                rubber_band.show()
            
            
            
            
            



                
            selected_features=self.mMapLayerComboBox_layers.currentLayer().selectedFeatures()
            number_of_selected_elements=len(selected_features)
            self.label_number_of_points.setText(str(number_of_selected_elements))












